cat <<EOF >> deployment.yml
apiVersion: v1
kind: Deployment
metadata:
  name: appdev
  namespace: dev
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLable:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      namespace: dev
    spec:
      - name: nginximage
        image: nginx:1.23
        ports:
          - containerport: 80
        resources:
          requests:
            cpu: "100m"
            memory: "200Mi"
          limits:
            cpu: "100m"
            memory: "200Mi"
EOF